version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - "node_modules"
            - package-lock.json
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run build
      - save_cache:
          paths:
            - "build"
          key: build-v1-{{ .Branch }}
      - run: ls -al
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - server.js
            - package.json
            - nightwatch-chrome.json
            - e2e
  test:
    docker:
      - image: gliscor/node-chrome-aws
    steps:
      - attach_workspace:
          at: .
      - run: pwd
      - run: ls -al
      - run: npm install -g pm2
      - run: pm2 start --name server node server.js
      - run: npm run e2e:chrome:headless
      - run: pm2 delete server

      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: .
      - run: ls -al
      - run: echo $DEPLOY_S3_BUCKET_NAME
      - aws-s3/copy:
          arguments: --recursive
          from: build
          to: s3://$DEPLOY_S3_BUCKET_NAME
workflows:
    build-and-test:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - build
              - test