version: 2.1
jobs:
  build-and-test:
    docker:
      - image: gliscor/node-chrome-aws
    steps:
      - checkout
      - run: ls -al
      - run: npm install
      - run: npm build
      - run: npm run e2e:chrome:headless
workflows:
    build-and-test:
      jobs:
        - build-and-test